high_scores:  # Daftar high scores dengan level dan skor awal
# Setiap entri memiliki nomor urut, level, nama pemain, dan skor
  1:
    level: Mini
    name: null
    score: 0
  2:
    level: Normal
    name: null
    score: 0
  3:
    level: Pro
    name: null
    score: 0
  4:
    level: Pro Max
    name: null
    score: 0
# Saat ini, nama pemain masih kosong dan skor diatur menjadi 0

levels: 
# tiap entri punya level berbeda, waktu, dan jumlah kata yang harus ditemukan
  1:
    name: Easy
    time: 900
    words: 12
  2:
    name: Medium
    time: 600
    words: 14
  3:
    name: Hard
    time: 300
    words: 16
  4:
    name: Maksimal
    words: 18
# Tingkat kesulitan meningkat seiring dengan penurunan waktu dan peningkatan jumlah kata.
max_time: 5 # maksimal waktu yang diberikan untuk menyelesaikan tiap level

player:
# Informasi tentang pemain saat ini
  level: 1
  name: efsfa
  score: 0
word_count: 12 # Jumlah kata yang harus ditemukan dalam setiap level
words_count: 8 # Jumlah total kata yang tersedia dalam permainan
